# Generated by Django 3.2.4 on 2022-01-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('passward', models.CharField(max_length=20, verbose_name='密码')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否活跃')),
                ('is_check', models.BooleanField(default=False, verbose_name='是否检查')),
                ('createimg', models.ImageField(null=True, upload_to='userimgs/', verbose_name='生产许可证')),
            ],
            options={
                'verbose_name': '用户数据表',
                'db_table': 'USER',
            },
        ),
    ]
