# Generated by Django 3.2.4 on 2022-01-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0002_alter_user_passward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passward',
            new_name='password',
        ),
    ]
