# Generated by Django 3.2.4 on 2022-01-04 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_rename_passward_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40, unique=True, verbose_name='厂商名')),
                ('finfo', models.CharField(max_length=1000, verbose_name='厂商信息')),
                ('faddress', models.CharField(max_length=500, verbose_name='厂商地址')),
            ],
            options={
                'verbose_name': '厂商数据表',
                'db_table': 'FACTORY',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanage.factory'),
        ),
    ]
