# Generated by Django 3.2.4 on 2022-01-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0005_auto_20220104_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='flogo',
            field=models.CharField(max_length=500, null=True, verbose_name='厂商logo'),
        ),
    ]
