# Generated by Django 3.2.4 on 2022-01-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0006_factory_flogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='faddress',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='厂商地址'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='finfo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='厂商信息'),
        ),
    ]
