# Generated by Django 3.2.4 on 2022-01-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanage', '0006_factory_flogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=300, verbose_name='车型名称')),
                ('sprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='指导价格')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('sinfo', models.TextField(null=True, verbose_name='车型信息')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.factory')),
            ],
            options={
                'verbose_name': '车型数据表',
                'db_table': 'SERIES',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='销售数量')),
                ('date', models.DateField(verbose_name='销售月份')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanage.series')),
            ],
            options={
                'verbose_name': '销量数据表',
                'db_table': 'SALES',
            },
        ),
    ]
