# Generated by Django 3.2.4 on 2022-01-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanage', '0002_alter_series_sinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='stype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='车型类型'),
        ),
    ]
