# Generated by Django 3.2.4 on 2022-01-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanage', '0003_series_stype'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='simage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='车型图片'),
        ),
    ]
